#!/usr/bin/env bash

ssource=$1
output=$2

RDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
libexec="$RDIR/../libexec/"

PATH="$PATH:$libexec"

set -e
is-generate-makefile.php $ssource Makefile.$ssource
is-generate-c.php $ssource
